apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: csharp138
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: csharp138 
  name: csharp138
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: csharp138
    weight: 100 
