apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: csharp138
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: csharp138 
  name: csharp138
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: csharp138 
